### ISSUE TITLE
Filename doesn't work when saving a file

### ISSUE THREAD

**Issue by TheDarkTiger** [shards-7/fakeyou.py#1]
Filename is unused in function "generate_ijt()", but should be used instead in fuction "say()"

Here is the fix:
```
diff --git a/fakeyou/fakeyou.py b/fakeyou/fakeyou.py
index 31c56a1..7566fc4 100644
--- a/fakeyou/fakeyou.py
+++ b/fakeyou/fakeyou.py
@@ -89,7 +89,7 @@ class FakeYou():

                return search(vjson=vjson,cjson=cjson)

-       def generate_ijt(self,text:str,ttsModelToken:str,filename:str="fakeyou.wav"):
+       def generate_ijt( self,text:str,ttsModelToken:str ):
                if self.v:
                        print("getting job token")
                payload={"uuid_idempotency_token":str(uuid4()),"tts_model_token":ttsModelToken,"inference_text":text}
@@ -128,8 +128,8 @@ class FakeYou():
                                raise TooManyRequests("Too many requests, try again later or use a proxy.")

        def say(self,text:str,ttsModelToken:str,filename:str="fakeyou.wav",cooldown:int=3):
-               ijt=self.generate_ijt(text=text,ttsModelToken=ttsModelToken,filename=filename)
-               return self.get_wav(ijt,cooldown=cooldown)
+               ijt=self.generate_ijt( text=text, ttsModelToken=ttsModelToken )
+               return self.get_wav( ijt, cooldown=cooldown, filename=filename )

        def get_tts_leaderboard(self):
                handler=self.session.get(self.baseurl+"leaderboard")
```

**Comment by FRIKIdelTO** [comment]
That's right
Need to add `filename `argument to `return `in `say `function:
`return self.get_wav(ijt,cooldown=cooldown,filename=filename)
`please, fix it ASAP

**Comment by TheDarkTiger** [comment]
That's what the fix I proposed does, yes.
Maybe a pull request would be easier?
If so, I may do it.

**Comment by justlearntutors** [comment]
Same bug on my pc.
Change
return self.get_wav(ijt,cooldown=cooldown)
to
return self.get_wav(ijt,cooldown=cooldown,filename=filename)

**Comment by ohquared** [comment]
just rename the audio after it creates, only need to import os.
fy.say(text='text', ttsModelToken=token,cooldown=5)
os.rename('fakeyou.wav', 'name_final.wav')

**Comment by TheDarkTiger** [comment]
@ohquared That's an horrible way to do it.
First because the function don't act as it should (as you can specify the name and it don't use it),
And second because renaming file without check if it was created or whatever is not good (and if the lib is updated later, your code will crash too).

Just save my fix as "fix.patch", and then invoke:
`git apply fix.patch`

**Comment by shards-7** [comment]
thanks for letting me know, @unknownZandbak already fixed it and i merged the pull, if y'all interested to maintain this library with me, please DM me :

Telegram, Instagram : thedemonicat
Discord : thedemonicat#9335
